### ISSUE TITLE
The bot no longer responds to the user if command execution fails

### ISSUE THREAD

**Issue by Octol1ttle** [TeamOctolings/Octobot#281]
### Description

![image](https://github.com/TeamOctolings/Octobot/assets/61277953/64afc77e-00b4-4ec8-ba8e-24e32c76902d)

### Expected vs. Actual Behavior

The expected behavior is that the bot responds to the user notifying them that an error occurred

The actual behavior is that the bot gets stuck with `is thinking` status

### Reproduction Steps

1. Try to run a command that returns an error

### Other Information

Suspects:
#275 (merged 3 hours ago as of writing)
#268 (merged yesterday as of writing)

**Comment by mctaylors** [comment]
Can't repro.

![image](https://github.com/TeamOctolings/Octobot/assets/95250141/8d404c2d-0b61-45d9-a108-71041dcf3ece)

**Comment by Octol1ttle** [comment]
I have pushed a branch containing reproduction code for this issue. Run /ping to get the error

**Comment by mctaylors** [comment]
Still can't repro, sorry.

![image](https://github.com/TeamOctolings/Octobot/assets/95250141/e8fa2f12-ba53-4ae9-8564-15da01c3fad0)
