### ISSUE TITLE
Reset an important setting if it is malfunctioned

### ISSUE THREAD

**Issue by mctaylors** [TeamOctolings/Octobot#298]
yeah that's not acceptable

_Originally posted by @Octol1ttle in https://github.com/TeamOctolings/Octobot/pull/297#discussion_r1546406056_

**Comment by Octol1ttle** [comment]
The title means to me that the planned change is to add a catch-all reset (if anything fails, just reset). However I don't think that's a good path. Each breaking change needs to have it's own correction. For #297, there would be code that, for example, changes `mctaylors-ru` to plain `ru`.
