### ISSUE TITLE
Add Splatoon™ splashtags in /about

### ISSUE THREAD

**Issue by Khowst** [TeamOctolings/Octobot#310]
### Description

self explanatory

### Proposed Solution

add dev splashtags to Octobot's /about

**Comment by mctaylors** [comment]
and how do you think it is supposed to look like?

**Comment by Khowst** [comment]
emojis, images or stickers, but in future it would be possible with [new media gallery](https://github.com/Discord-Datamining/Discord-Datamining/assets/28404851/7bd0683e-cc6e-4917-ad1b-493b39d6a95b)

**Comment by mctaylors** [comment]
no I think this will be hard to implement + requires too much embed space
