### ISSUE TITLE
Add more types of events to log

### ISSUE THREAD

**Issue by sionit1337** [TeamOctolings/Octobot#318]
### Description

Add more types of events to log, like role create/delete/rename, channel create/delete/rename and so on

### Proposed Solution

Add an `EventsToLog` setting with possible values ​​`all` (log all events), `default` (log only deleting/editing messages, joining/leaving members, bans/kicks/mutes), `off`/`disable` (don't log anything)

**Comment by Octol1ttle** [comment]
Octobot provides logging for actions where audit logs may not provide sufficient information. Logging all events would require reimplementing the whole audit log and keeping that implementation up-to-date with Discord's new events. If you have specific actions that require more context than audit logs provide, please specify them explicitly.

**Comment by Octol1ttle** [comment]
Closing due to lack of response. If you wish to follow up on this issue, we will reopen it.
